# Generated by Django 2.0.6 on 2018-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('pathology', models.CharField(blank=True, max_length=128, null=True, verbose_name='病理号')),
                ('file_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名')),
                ('resolution', models.CharField(blank=True, max_length=16, null=True, verbose_name='分辨率')),
                ('storage_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='存储路径')),
                ('waveplate_source', models.CharField(blank=True, max_length=64, null=True, verbose_name='片源')),
                ('is_learn', models.CharField(blank=True, max_length=16, null=True, verbose_name='是否学习')),
                ('diagnosis_label_doctor', models.CharField(blank=True, max_length=64, null=True, verbose_name='医生诊断标签')),
                ('diagnosis_label_zhu', models.CharField(blank=True, max_length=64, null=True, verbose_name='朱博士诊断标签')),
                ('making_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='切片制式')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tb_big_image_info',
                'verbose_name': '大图信息',
                'verbose_name_plural': '大图信息',
            },
        ),
    ]
