# Generated by Django 2.0.6 on 2018-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRenameRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('pathology', models.CharField(blank=True, max_length=128, null=True, verbose_name='病理号')),
                ('current_file_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='当前文件名')),
                ('his_name1', models.CharField(blank=True, max_length=128, null=True, verbose_name='曾用名1')),
                ('his_name2', models.CharField(blank=True, max_length=128, null=True, verbose_name='曾用名2')),
                ('his_name3', models.CharField(blank=True, max_length=128, null=True, verbose_name='曾用名3')),
                ('his_name4', models.CharField(blank=True, max_length=128, null=True, verbose_name='曾用名4')),
                ('his_name5', models.CharField(blank=True, max_length=128, null=True, verbose_name='曾用名5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tb_rename',
                'verbose_name': '文件更名记录',
                'verbose_name_plural': '文件更名记录',
            },
        ),
    ]
