# Generated by Django 2.0.6 on 2018-12-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileRenameRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerenamerecord',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
    ]
