# Generated by Django 2.0.6 on 2019-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseZhu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnoseZhuTmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('pathology', models.CharField(blank=True, max_length=128, null=True, verbose_name='病理号')),
                ('his_diagnosis_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='朱博士历史诊断标签')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'tb_diagnose_zhu_tmp',
                'verbose_name_plural': '朱博士历史诊断标签临时表',
                'verbose_name': '朱博士历史诊断标签临时表',
            },
        ),
        migrations.AlterField(
            model_name='diagnosezhu',
            name='his_diagnosis_label',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='朱博士历史诊断标签'),
        ),
    ]
