# Generated by Django 2.0.6 on 2019-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseZhu', '0002_auto_20190213_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosezhutmp',
            name='his_diagnosis_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='朱博士历史诊断标签'),
        ),
    ]
