# Generated by Django 2.0.6 on 2018-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('pathology', models.CharField(blank=True, max_length=128, null=True, verbose_name='病理号')),
                ('age', models.CharField(blank=True, max_length=64, null=True, verbose_name='年龄')),
                ('last_menstruation', models.CharField(blank=True, max_length=128, null=True, verbose_name='末次经期时间')),
                ('review_time', models.CharField(blank=True, max_length=128, null=True, verbose_name='审核时间')),
                ('sampling_time', models.CharField(blank=True, max_length=128, null=True, verbose_name='采样时间')),
                ('diagnose_result_doctor', models.CharField(blank=True, max_length=128, null=True, verbose_name='医生诊断结果')),
                ('diagnosis_label_doctor', models.CharField(blank=True, max_length=64, null=True, verbose_name='医生诊断标签')),
                ('what_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='不明时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tb_case_info',
                'verbose_name': '病例信息',
                'verbose_name_plural': '病例信息',
            },
        ),
    ]
