# Generated by Django 2.0.6 on 2018-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一主键')),
                ('his_diagnosis_label', models.CharField(blank=True, max_length=64, null=True, verbose_name='朱博士历史诊断标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tb_image_diagnosis_zhu',
                'verbose_name': '朱博士历史诊断标签',
                'verbose_name_plural': '朱博士历史诊断标签',
            },
        ),
    ]
